FROM ubuntu:latest

RUN apt-get update && apt-get install -y bash man-db

RUN apt-get update && apt-get install -y unminimize

RUN yes | unminimize

COPY Task.sh /Task.sh

RUN chmod +x /Task.sh

CMD ["sh", "/Task.sh"]